-- Seed two-level category taxonomy (SPEC.md §4). Users can add/rename later.

INSERT INTO categories (name, parent_id, is_income) VALUES
    ('Income',            NULL, TRUE),
    ('Food & Dining',     NULL, FALSE),
    ('Housing',           NULL, FALSE),
    ('Bills & Utilities', NULL, FALSE),
    ('Transportation',    NULL, FALSE),
    ('Shopping',          NULL, FALSE),
    ('Entertainment',     NULL, FALSE),
    ('Health & Wellness', NULL, FALSE),
    ('Travel',            NULL, FALSE),
    ('Personal Care',     NULL, FALSE),
    ('Education',         NULL, FALSE),
    ('Gifts & Donations', NULL, FALSE),
    ('Fees & Charges',    NULL, FALSE),
    ('Cash & ATM',        NULL, FALSE),
    ('Uncategorized',     NULL, FALSE);

INSERT INTO categories (name, parent_id, is_income)
SELECT child.name, parent.id, parent.is_income
FROM (VALUES
    ('Paycheck',                 'Income'),
    ('Interest Income',          'Income'),
    ('Refunds & Reimbursements', 'Income'),
    ('Other Income',             'Income'),
    ('Groceries',                'Food & Dining'),
    ('Restaurants',              'Food & Dining'),
    ('Coffee Shops',             'Food & Dining'),
    ('Fast Food',                'Food & Dining'),
    ('Food Delivery',            'Food & Dining'),
    ('Alcohol & Bars',           'Food & Dining'),
    ('Rent & Mortgage',          'Housing'),
    ('Home Improvement',         'Housing'),
    ('Home Supplies',            'Housing'),
    ('Electric & Gas',           'Bills & Utilities'),
    ('Internet & Phone',         'Bills & Utilities'),
    ('Water & Trash',            'Bills & Utilities'),
    ('Gas & Fuel',               'Transportation'),
    ('Rideshare & Taxi',         'Transportation'),
    ('Public Transit',           'Transportation'),
    ('Parking & Tolls',          'Transportation'),
    ('Auto Maintenance',         'Transportation'),
    ('Auto Insurance',           'Transportation'),
    ('General Merchandise',      'Shopping'),
    ('Clothing',                 'Shopping'),
    ('Electronics',              'Shopping'),
    ('Streaming Services',       'Entertainment'),
    ('Movies & Events',          'Entertainment'),
    ('Hobbies',                  'Entertainment'),
    ('Games',                    'Entertainment'),
    ('Pharmacy',                 'Health & Wellness'),
    ('Doctor & Dental',          'Health & Wellness'),
    ('Fitness',                  'Health & Wellness'),
    ('Health Insurance',         'Health & Wellness'),
    ('Flights',                  'Travel'),
    ('Lodging',                  'Travel'),
    ('Rental Cars',              'Travel'),
    ('Hair & Beauty',            'Personal Care'),
    ('Laundry & Dry Cleaning',   'Personal Care'),
    ('Tuition & Courses',        'Education'),
    ('Books & Supplies',         'Education'),
    ('Gifts',                    'Gifts & Donations'),
    ('Charity',                  'Gifts & Donations'),
    ('Bank Fees',                'Fees & Charges'),
    ('Interest Charges',         'Fees & Charges'),
    ('ATM Fees',                 'Fees & Charges')
) AS child(name, parent_name)
JOIN categories parent ON parent.name = child.parent_name;
